### ISSUE TITLE
Query transaction history of multiple addresses at once

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#13]
Add ability to query transaction history of multiple addresses at once and have the pagination working for that set of addresses.

From FAT Discord:

luap

@AdamSLevy I'd like to discuss the possibility to have an API to query the past transactions of multiple addresses at once with pagination (for use in the wallet). Currently I can query for the past transactions of a single address and paginate for that address. But in the wallet I have multiple addresses of the user, and paginating properly the aggregation of the result of individual addresses is a nightmare. I believe it would be straight forward and much more efficient to implement in fatd (as it would simply be a small modification of your SQL query?)

AdamSLevy

good idea.
I can add that.
Easy to add the sql
Can we change the params to accept an array of addresses even if it's a single one?
So I remove the "address" field and replace it with "addresses" which is an array
I could support both actually if you think that's valuable.
But I'd make them mutually exclusive.

luap

always array is fine to me

**Comment by AdamSLevy** [comment]
@PaulBernier please close this issue if the latest commit correctly implements this feature request.

**Comment by PaulBernier** [comment]
This is looking good @AdamSLevy, resolving, thanks.
