### ISSUE TITLE
Add a method returning pending transactions

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#14]
Along the lines of https://github.com/Factom-Asset-Tokens/fatd/issues/8 (but less critical), having a method returning pending transactions would allow to enhance the user experience in the wallet. It would allow the user to immediately see that his transaction was submitted and is in pending (new block) state.

**Comment by AdamSLevy** [comment]
Please let me know if this can be closed as of the latest commit on develop.

**Comment by AdamSLevy** [comment]
Pending transactions can be retrieved using the normal "get-transactions" API with the "includepending":true param included. Any pending transactions will include "pending":true
