### ISSUE TITLE
Set commit version and api version headers for all RPC requests

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#16]
Make fatd set HTTP headers specifying its commit version & API version in RPC requests. Useful for clients to preemptively detect compatibility issues without needing to parse a potentially incompatible request body.

**Comment by drkatz** [comment]
Proposed headers `Fatd-Version` and `Fatd-Api-Version`

**Comment by AdamSLevy** [comment]
Should be part of current release.
