### ISSUE TITLE
metadata not populated for both fat0 and fat1 transactions

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#22]
```bash
$ ./fat-cli --version
fat-cli:  v0.4.2.r38.ge5c9222
fatd:     v0.4.2.r38.ge5c9222
fatd API: 1
```

Adding `-m '"coinbase TX"'` to a `transact` command doesn't result in the transaction having this meta data attached. I can tell the value of the metadata flag is parsed because I can get an "invalid JSON error" if the value is wrong. But if correct, it seems to simply never make it to the actual transaction.

**Comment by PaulBernier** [comment]
Looking from far away, I'd say the metadata variable is never used to populate the metadata of the transaction structure: https://github.com/Factom-Asset-Tokens/fatd/blob/develop/cli/cmd/transact.go#L34

**Comment by AdamSLevy** [comment]
Ah. Thank you. I think you are right in your diagnosis of the bug. Will fix very soon.
