### ISSUE TITLE
Stricter `get-transactions` pagination

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#23]
Right now querying page 0 and page 1 is allowed and return the same result. I think this behavior is a risk of confusion and mistake for the user that wouldn't pay attention enough (like myself).

Let's go with a stricter 1based pagination:

- Default page to 1
- Reject a page of 0 (and small of course)

**Comment by AdamSLevy** [comment]
Latest commit on develop should fix this.
