### ISSUE TITLE
Glibc 2.28 dependency for binaries means they don't run on Ubuntu Bionic or Debian Stretch

### ISSUE THREAD

**Issue by mberry** [Factom-Asset-Tokens/fatd#24]
```bash
root@fatd:~# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

root@fatd:~# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

root@fatd:~# ./fatd
./fatd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./fatd)
```

Ubuntu Cosmic or Debian Buster(testing) seem to be fine.

**Comment by AdamSLevy** [comment]
This is always going to be an issue for some Linux distributions or any system with a different glibc version. We cannot accommodate all Linux distros with the pre built releases. That is the role of distribution specific package maintainers. 

Fortunately, using the Makefile and a latest version of Golang, it is very straightforward to build fatd and fat-cli against your system's glibc. Please open a new issue if you have problems building.

I'm afraid I must close this as Won't Fix.

**Comment by AdamSLevy** [comment]
In the future we can re-evaluate providing binaries for the GCC toolchain Ubuntu 18 uses.
