### ISSUE TITLE
Panic caused by control-c interrupt

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#31]
To reproduce from a fresh database directory, develop commit `273adaa88e9e2d2e62822241c71e14c29ebd84ff`:

1. `./fatd -ecadr <ec> -debug -networkid=0x883e093b -dbpath <path> -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df 962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`
2. Wait until sync completed
3. Hit control+c to interrupt the fatd process
4. Get this: https://gist.github.com/drkatz/3087dc7be81d29abb452614391a5ce76

**Comment by AdamSLevy** [comment]
I could not reproduce this on the latest commit.

**Comment by drkatz** [comment]
I am still getting this issue on the latest version
A reproduced debug:
https://gist.github.com/drkatz/dbe5661367f8b68152400ec3dc113dce

The command:
```./fatd -ecadr <EC> -debug -networkid=test -dbpath /home/devon/git-projects/fatd/fat.db -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df,962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f```

**Comment by drkatz** [comment]
After this happens it totally corrupts everything, impossible to restart the daemon. Recieve:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x74ceb7]

goroutine 1 [running]:
crawshaw.io/sqlite/sqlitex.(*Pool).Close(0x0, 0x3000000008ff0e0, 0xffffffffffffffff)
        /home/devon/go/pkg/mod/github.com/!adam!s!levy/sqlite@v0.1.3-0.20190925021041-5f14912819e9/sqlitex/pool.go:168 +0x37
github.com/Factom-Asset-Tokens/fatd/db.(*Chain).Close(0xc000259c58)
        db/chain.go:249 +0x36
github.com/Factom-Asset-Tokens/fatd/engine.ChainMap.Close(0xc0000a4ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf6f040)
        engine/chainmap.go:119 +0x165
github.com/Factom-Asset-Tokens/fatd/engine.loadChains.func1(0xc00025ba68, 0xc00025ab90)
        engine/chainmap.go:137 +0x113
github.com/Factom-Asset-Tokens/fatd/engine.loadChains(0xc00001064a, 0xa2a500, 0xc000405ce0)
        engine/chainmap.go:181 +0xcc3
github.com/Factom-Asset-Tokens/fatd/engine.Start(0xc000170000, 0x0)
        engine/engine.go:109 +0x4af
main._main(0x0)
        main.go:57 +0x275
main.main()
        main.go:35 +0x22
```
