### ISSUE TITLE
Panic after send-transaction

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#32]
To reproduce from a clean database directory, develop commit `273adaa88e9e2d2e62822241c71e14c29ebd84ff`:

1. `./fatd -ecadr <ec> -debug -networkid=0x883e093b -dbpath <path> -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df 962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`
2. Wait until sync completed
3. Send a normal FAT-0 transaction on chain `0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df`, for example entryhash `7524c9ec2b7ceeb7494d581a16af2ff72c47842ec1df02313ae3d5b1f8450e46`, without pending transactions
3. Hit control+c to interrupt the fatd process
4. Get the panic debug from #31 
5. Restart fatd with the same command as above
6. Get this panic: https://gist.github.com/drkatz/51358eed19fa6c65fe72d3bcb3cb5bb4

**Comment by AdamSLevy** [comment]
Cannot reproduce on latest commit.
