### ISSUE TITLE
Panic caused by calling get-issuance with includepending = true

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#33]
Steps to reproduce on commit `273adaa88e9e2d2e62822241c71e14c29ebd84ff`:
1.Sync fatd from scratch: `./fatd -ecadr <ec> -debug -networkid=0x883e093b -dbpath <path> -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df 962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`
2.Call get-issuance with `"includepending":true`
3. Get this panic: https://gist.github.com/drkatz/31b8e74f993818aca2281a58c6219283

**Comment by AdamSLevy** [comment]
Can't reproduce on latest commit. I believe I resolved this through some changes to how I do pending txs.
