### ISSUE TITLE
Incorrect chain ID returned with pending transaction result[BUG]

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#42]
**Describe the bug**
On a fat daemon with one fat-0 and one fat-1 whitelisted chain, sending a pending transaction on the FAT-0 chain results in the FAT-1 chain ID being returned in the result JSON

**Describe the environment (please complete the following)**
- OS: Ubuntu 18.08
- Factom Network: testnet
- `fatd` State: synced
- `fatd` Version: v0.6.0.r71.ge269f60

**To Reproduce**
1. start fatd
2. Wait for sync
3. Send FAT-0 transaction wiht pending true
4. Observe incorrect chain ID in response JSON

**Expected behavior**
FAT-0 chain ID is returned in request

**Comment by AdamSLevy** [comment]
I cannot reproduce this bug. I get the correct chain ID back with the "send-transaction" API

**Comment by drkatz** [comment]
This panic occurs associated with this issue after a fresh sync and running the fat-js test suite:
https://gist.github.com/drkatz/b7441475be2682f4a4f3ec76786f34fa

Please note this **ONLY** occurs with whitelisting chains. I cannot reproduce this otherwise. The two testnet chains I'm whitelisting here are:
`0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df`
`962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`

The command I'm using:
`./fatd -ecadr <EC> -debug -networkid=test -dbpath /home/devon/git-projects/fatd/fat.db -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df,962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`

**Comment by AdamSLevy** [comment]
reproduced and fixed.
