### ISSUE TITLE
Sqlite panic after indeterminate delay [BUG]

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#43]
**Describe the bug**
Some time after starts up the daemon crashes with a sqlite related error

**Describe the environment (please complete the following)**
OS: Ubuntu 18.08
Factom Network: testnet
fatd State: synced
fatd Version: v0.6.0.r71.ge269f60

**To Reproduce**
1. Start fatd ```./fatd -ecadr <EC> -debug -networkid=test -dbpath /home/devon/git-projects/fatd/fat.db -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df,962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f```
2. Wait for sync
4. Wait some time, usually < 3 mins
5. Panic occurs

**Expected behavior**
Normal operation

**Output**
https://gist.github.com/drkatz/7383be65cc37081bcdc05f49538735c6

**Additional context**
none

**Comment by drkatz** [comment]
Reproduced on latest version v0.6.0.r76.g9cf3893+
https://gist.github.com/drkatz/9dd66b408b84f0a0232a0911b32b7b1a

**Comment by AdamSLevy** [comment]
I don't think this is reproducible anymore. please re open if it reoccurs.

**Comment by drkatz** [comment]
Another reproduction of the issue on version `v0.6.0.r82.g35f8262 ` from a fresh sync
https://gist.github.com/drkatz/bd16f41873680b22298d7c65b57f3de6

**Comment by AdamSLevy** [comment]
A conn from the read only pool is getting garbage collected well before it ever should. I will run additional GC to try to reproduce more reliably

**Comment by AdamSLevy** [comment]
OK I finally was able to reproduce this. The issue I had in reproducing it was not using -whitelist or removing the database files. The path for loading whitelisted chains that do not yet have a database is different than loading whitelisted chains that already have an existing database. 

This is now solved in the latest commit on develop.

**Comment by drkatz** [comment]
Experiencing this on version `v0.6.0.r84.g90575c4`:
https://gist.github.com/drkatz/dc7988449398c8db47c5bc6db80ee285

This time it was from a database that was already synced I believe. This time it says `open *sqlite.Session garbage collected, call Delete method` instead of `Close method`

**Comment by AdamSLevy** [comment]
reproduced and again fixed.
