### ISSUE TITLE
Panic when running get-balances[BUG]

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#46]
**Describe the bug**
Calling get-balances causes a panic

**Describe the environment (please complete the following)**
- OS: Ubuntu 18.01
- Factom Network: testnet
- `fatd` State: synced
- `fatd` Version: v0.6.0.r84.g90575c4
- `fat-cli` Version: v0.6.0.r84.g90575c4

**To Reproduce**
1. `./fatd -ecadr EC1tE4afVGPrBUStDhZPx1aHf4yHqsJuaDpM7WDbXCcYxruUxj2D -debug -networkid=test -dbpath /home/devon/git-projects/fatd/fat.db -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df,962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f`
2. Wait for sync ...
3. Run fat-js test suite
4. Experience non-fatal panic

**Expected behavior**
Normal operation

**Output**
https://gist.github.com/drkatz/e49d19778dfa3fa81e26247917e8ab39

**Additional context**
This happened once and have not had luck reproducing yet. Perhaps the debug can help find the issue

**Comment by AdamSLevy** [comment]
This is related to the rw mutex not being initialized. Did the databases exist prior to startup?

**Comment by drkatz** [comment]
I believe this was a fresh sync (not 100% but more like 85% sure)

**Comment by AdamSLevy** [comment]
reproduced and fixed.
