### ISSUE TITLE
Internal server error with pending transactions[BUG]

### ISSUE THREAD

**Issue by drkatz** [Factom-Asset-Tokens/fatd#47]
**Describe the bug**
Random 500 ISE related to checking for pending txs occurs causing fatd to panic and crash

**Describe the environment (please complete the following)**

OS: Ubuntu 18.01
Factom Network: testnet
fatd State: synced
fatd Version: v0.6.0.r84.g90575c4
fat-cli Version: v0.6.0.r84.g90575c4

**To Reproduce**
1. ./fatd -ecadr EC1tE4afVGPrBUStDhZPx1aHf4yHqsJuaDpM7WDbXCcYxruUxj2D -debug -networkid=test -dbpath /home/devon/git-projects/fatd/fat.db -whitelist 0cccd100a1801c0cf4aa2104b15dec94fe6f45d0f3347b016ed20d81059494df,962a18328c83f370113ff212bae21aaf34e5252bc33d59c9db3df2a6bfda966f
2. Wait for sync ...
3. Wait for indeterminate panic

**Expected behavior**
Normal behavior

**Output**
https://gist.github.com/drkatz/b279c4d855300feb1d0af131ee368bf2

**Additional context**
Seems to happen randomly?

**Comment by AdamSLevy** [comment]
The EOF was an error from factomd. the non-clean shutdown was due to the bug fixed in the latest commit.
