### ISSUE TITLE
Improvements for `get-transactions` fatd API

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#5]
Discussed on Discord:
* Rename parameter `start` to `page`. Reduce possible confusion as `entryhash` is the real starting point.
* Add a parameter for ability to get newest transactions first (i.e choosing ordering of the results).
* Keep default result ordering as "oldest first".

**Comment by AdamSLevy** [comment]
Commit 8a193cd44d002b06997db431d03befd0c4e8fd01 changes "start" to "page". And commit ba9870ceb4f6668e4e8bb1cd15301e8880009824 adds transaction ordering.
