### ISSUE TITLE
Support new Factom digital identity keys

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#7]
Add support for new Factom digital identity keys. Those are also on-chain identities with identity keys which follow a slightly different format `idpub.../idsec...`. Also we should think of which key of an identity to use (currently we arbitrarily chose sk1 for instance).

The FAT Wallet supports only those new identities so until fatd support them too it's impossible to use the wallet to issue a new token or emit coinbase transactions.

**Comment by AdamSLevy** [comment]
This turned out to not be the correct direction.
